name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      cassandra:
        # Docker Hub image
        image: cassandra:latest
        ports:
          - 9042:9042
          - 7000:7000

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        echo "deb https://debian.datastax.com/enterprise/ stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list
        curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y tcl-dev multiarch-support
        sudo apt-get install -y dse-libcassandra
        wget https://downloads.datastax.com/cpp-driver/ubuntu/18.04/dependencies/libuv/v1.35.0/libuv1_1.35.0-1_amd64.deb
        wget https://downloads.datastax.com/cpp-driver/ubuntu/18.04/dse/v1.10.3/dse-cpp-driver_1.10.3-1_amd64.deb
        wget https://downloads.datastax.com/cpp-driver/ubuntu/18.04/dse/v1.10.3/dse-cpp-driver-dev_1.10.3-1_amd64.deb
        sudo dpkg -i libuv1_1.35.0-1_amd64.deb
        sudo dpkg -i dse-cpp-driver_1.10.3-1_amd64.deb
        sudo dpkg -i dse-cpp-driver-dev_1.10.3-1_amd64.deb

    - name: configure
      run: |
        autoreconf
        ./configure
    - name: build
      run: make
    - name: install
      run: sudo make install
#    - name: test
#      run: make test

